variable "location" {}
variable "os_name" {}
variable "instance-type" {}
variable "instance_name" {}
variable "key" {}
variable "env_prefix" {}
variable "cidr_blocks" {}
variable "cidr_block" {}
variable "vpc_cidr_block" {}
variable "subnet_cidr_01" {}
variable "subnet_cidr_02" {}
variable "subent_az_01" {}
variable "subent_az_02" {}